[package]
name = "airos"
version = "1.0.0"
description = "The Air Operating System"
authors = ["air"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-beta.6", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = ["unstable"] }
tauri-plugin-shell = "2.0.0-beta.1"
tauri-plugin-store = "2.0.0-beta.1"
serde_json = "1.0"
bcrypt = "0.15.0"
portable-pty = "0.8.1"
serde = "1.0.197"
airos_wmctrl = { git = "https://github.com/madebyair/airos-wmctrl" }

[features]
custom-protocol = ["tauri/custom-protocol"]
