[package]
name = "airos"
version = "1.0.0"
description = "The Air Operating System"
authors = ["air"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = ["unstable"] }
tauri-plugin-shell = "2.0.0-beta.1"
tauri-plugin-store = "2.0.0-beta"
serde_json = "1.0"
bcrypt = "0.15.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
