name: Tauri

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - name: Run apt update
      run: sudo apt update
    - name: Install apt packages
      run: sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libssl-dev libayatana-appindicator3-dev librsvg2-dev
    - name: Install dependencies
      run: npm install
    - name: Run build
      run: npm run build
    - name: Upload bundle
      uses: actions/upload-artifact@v3
      with:
        name: AMD64 Build
        path: ${{ github.workspace }}/src-rust/target/release/airos

